<!DOCTYPE html>
<html>
<head>
    <title><?php echo $G->config["w_nombre"] ?> - <?php echo $G->title ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="shortcut icon" href="<?php echo $G->config["w_url"]."/app".DS."media".DS."images".DS."favicon.png" ?>">

    <!-- Cargar Recursos CSS -->
    <link rel="stylesheet" href="<?php echo $G->config["w_url"].DS."app".DS."media".DS."css".DS."bootstrap.min.css" ?>">
    <link rel="stylesheet" href="<?php echo $G->config["w_url"].DS."app".DS."media".DS."css".DS."font-awesome.min.css" ?>">
    <link rel="stylesheet" href="<?php echo $G->config["w_url"].DS."app".DS."media".DS."css".DS."AdminLTE.css" ?>">

</head>
<body>
<div class="container">