<ul class="sidebar-menu">
    <li class="treeview">

        <a href="#">
            <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
            <span>Preguntas</span>
            <i class="fa fa-angle-left pull-right"></i>
        </a>
            <ul class="treeview-menu">
                <li><a href="<?php echo $G->config['w_url'] ?>/preguntas/lista"><i class="fa fa-angle-double-right"></i> Lista de Preguntas</a></li>
            </ul>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-book"></i>
            <span>Reportes</span>
            <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="<?php echo $G->config['w_url'] ?>/reportes/preguntas"><i class="fa fa-angle-double-right"></i> Por Lenguaje</a></li>
        </ul>
    </li>
</ul>