<!DOCTYPE html>
<html>
    <head>
        <title><?php echo $G->config["w_nombre"] ?> - <?php echo $G->title ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <link rel="shortcut icon" href="<?php echo $G->config["w_url"] . "/app" . DS . "media" . DS . "images" . DS . "favicon.png" ?>">

        <!-- Cargar Recursos CSS -->
        <link rel="stylesheet" href="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "css" . DS . "bootstrap.min.css" ?>">
        <link rel="stylesheet" href="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "css" . DS . "font-awesome.min.css" ?>">
        <link rel="stylesheet" type="text/css" href="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "css" . DS . "datepicker/datepicker3.css" ?>">
        <link href="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "css" . DS . "chosen.css" ?>" rel="stylesheet">
        <!-- Ionicons -->
        <link href="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "css" . DS . "ionicons.min.css" ?>" rel="stylesheet" type="text/css" />
        <!-- Theme style -->
        <link href="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "css" . DS . "morris/morris.css" ?>" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "css" . DS . "AdminLTE.css" ?>">
        <!-- jQuery 2.0.2 -->
        <script src="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "js" . DS . "jquery-1.11.0.min.js" ?>"></script>
        <!-- Bootstrap -->
        <script src="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "js" . DS . "bootstrap.min.js" ?>" type="text/javascript"></script>
        <!-- AdminLTE App -->
        <script src="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "js" . DS . "AdminLTE/app.js" ?>" type="text/javascript"></script>

        <script src="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "js" . DS . "plugins/datepicker/bootstrap-datepicker.js" ?>" type="text/javascript"></script>
        <script src="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "js" . DS . "chosen.jquery.js" ?>"></script>
        <script src="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "js" . DS . "raphael-min.js" ?>" type="text/javascript"></script>
        <script src="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "js" . DS . "plugins/morris/morris.min.js" ?>" type="text/javascript"></script>
    </head>
    <body class="skin-blue">
        <header class="header">
            <a href="<?php echo $G->config['w_url']?>/home" class="logo">
                <!-- Add the class icon to your logo image or logo icon to add the margining -->
               <?php echo $G->config["w_nombre"] ?>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-right">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="glyphicon glyphicon-user"></i>
                                <span><?php echo $_SESSION['user'];?><i class="caret"></i></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="user-footer">
                                    <div class="pull-right">
                                        <a href="logout" class="btn btn-default btn-flat">Salir del sistema</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
