<style>
    .thumb {
        height: 300px;
        border: 1px solid #000;
        margin: 10px 5px 0 0;
    }
</style>
<section class="content-header">
    <h1>
        <?php echo strtoupper($G->act) . ' | '; ?> PREGUNTAS 
    </h1>
</section>
<link rel="stylesheet" href="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "css" . DS . "token-input.css" ?>">
<script src="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "js" . DS . "jquery.tokeninput.js" ?>" type="text/javascript"></script>

<section class="content">

    <div class="box box-danger">

        <?php if ($G->act == 'agregar') { ?>
            <div class="box-body">
                <form id="frmreg" method="post" class="form-horizontal" action="opcion">
                    <div class="col-lg-8">
                        <div class="form-group form-group-sm">
                            <label for="id" class="col-lg-2 control-label">Id</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" id="id" name="id" disabled>
                            </div>
                        </div>
                        <div class="form-group form-group-sm">
                            <label for="pregunta" class="col-lg-2 control-label">Pregunta</label>
                            <div class="col-lg-10">
                                <textarea style="resize: none; height: 50%" rows="4" pattern="[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ,.]{1,200}" data-valid-max="10" class="form-control" id="pregunta" name="pregunta" placeholder="Ingrese la pregunta" required></textarea>
                            </div>
                        </div>
                        <div class="form-group form-group-sm">
                            <label for="descripcion" class="col-lg-2 control-label">Descripci&oacute;n</label>
                            <div class="col-lg-10">
                                <textarea style="resize: none; height: 50%" rows="4" pattern="[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ,.]{1,200}" data-valid-max="10" class="form-control" id="descripcion" name="descripcion" placeholder="Ingrese la descripci&oacute;n" required></textarea>
                            </div>
                        </div>
                        <a class="btn btn-success btn-xs" data-toggle="modal" data-target="#agregaropciones" onclick="ocultar_mensaje()">A&ntilde;adir Opcion</a>
                        <div class="form-group form-group-sm">
                            <label for="opciones" class="col-lg-2 control-label">Opciones</label>
                            <div class="col-lg-10">
                                <input id="token-input-opciones" name="token-input-opciones" type="text" class="form-control" placeholder="Ingrese opciones de respuestas" required>
                            </div>
                        </div>

                        <div class="form-group form-group-sm">
                            <label for="respuesta" class="col-lg-2 control-label">Respuesta</label>
                            <div class="col-lg-10">
                                <select id="respuesta" name="respuesta" class="form-control">
                                    <option value="#">Ingrese la respuesta</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group form-group-sm">
                            <label for="sesion" class="col-lg-2 control-label">Nivel</label>
                            <div class="col-lg-4">
                                <input type="text" class="form-control" id="sesion" name="sesion"  disabled>
                            </div>
                            <label for="tipo" class="col-lg-2 control-label">Tipo</label>
                            <div class="col-lg-4">
                                <select id="tipo" name="tipo"  class="form-control">
                                    <option value="principiante">Principiante</option>
                                    <option value="intermedio">Intermedio</option>
                                    <option value="avanzado">Avanzado</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group form-group-sm">
                            <div class="col-lg-6 col-lg-offset-4">
                                <a href="index"  class="btn btn-default">Atr&aacute;s</a>
                                <button type="reset" class="btn btn-danger" >Cancelar</button>
                                <button type="submit" class="btn btn-primary">Agregar</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!-- MODAL AGREGAR RESPUESTAS-->
            <div class="modal fade" id="agregaropciones" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h4 class="modal-title" id="myModalLabel">Agregar Respuesta</h4>
                        </div>
                        <div class="modal-body">
                            <div class="form-group form-group-sm">
                                <label>Respuesta</label>
                                <input type="text" class="form-control" placeholder="Ingrese opcion" name="agregar_opcion" id="agregar_opcion"/>
                            </div>
                            <div class="alert alert-success" id="estado_agregar"></div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                            <button type="button" class="btn btn-primary" onclick="agregar()">Agregar</button>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                var arr = [];
                var seleccionados = [];
                var letra = 1;
                var literal_seleccionado = 0;
                function agregar() {

                    var opcion = document.getElementById('agregar_opcion').value;

                    arr.push({id: letra, name: opcion});
                    document.getElementById('estado_agregar').innerHTML = "Se ha agregado correctamente";
                    document.getElementById('estado_agregar').style.visibility = "visible";
                    // console.log(JSON.stringify(arr, null, 4));
                    letra++;
                }
                function ocultar_mensaje() {
                    document.getElementById('estado_agregar').style.visibility = "hidden";
                }
                function imprimir() {
                    for (var i in seleccionados)
                    {
                        if (!isNaN(seleccionados[i].id))
                            if (seleccionados[i].id > 0)
                                console.log(seleccionados[i].id + ": " + seleccionados[i].name);
                    }

                }
                $(document).ready(function () {
                    var sel = document.getElementById('respuesta');
                    $("#token-input-opciones").tokenInput(arr,
                            {
                                preventDuplicates: true,
                                onAdd: function (item) {

                                    var opt = document.createElement('option');
                                    opt.appendChild(document.createTextNode(item.name));
                                    opt.value = item.name;
                                    opt.id = item.id;
                                    sel.appendChild(opt);
                                    var myOpts = document.getElementById('respuesta').options;
                                    for (var i in myOpts) {
                                        seleccionados.pop();
                                    }
                                    for (var i in myOpts) {
                                        seleccionados.push({id: i, name: myOpts[i].value});
                                    }

                                    literal_seleccionado++;
                                },
                                onDelete: function (item) {
                                    var item = document.getElementById(item.id);
                                    item.parentNode.removeChild(item);
                                    var myOpts = document.getElementById('respuesta').options;
                                    for (var i in myOpts) {
                                        seleccionados.pop();
                                    }
                                    for (var i in myOpts) {
                                        seleccionados.push({id: i, name: myOpts[i].value});
                                    }
                                    //   console.log("Borrando->"+ (item.id-1)+" : "+seleccionados[item.id-1].id + " <-> " + seleccionados[item.id-1].name);
                                    // delete seleccionados[item.id-1];
                                    // console.log(JSON.stringify(seleccionados, null, 4));
                                    //literal_seleccionado--;
                                },
                                onResult: function (results) {

                                    $.each(results, function (index, value) {
                                        value.name = value.name + "2";
                                    });

                                    return results;
                                }
                            });
                });
            </script>
        <?php } ?>
    </div>
</section>
