<ul class="sidebar-menu">
    <li class="treeview">

        <a href="#">
            <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
            <span>Preguntas</span>
            <i class="fa fa-angle-left pull-right"></i>
        </a>
        <?php
        if ($G->user->data->u_tipo == 1) {
            ?>
            <ul class="treeview-menu">
                <li><a href="<?php echo $G->config['w_url'] ?>/preguntas/agregar"><i class="fa fa-angle-double-right"></i> Agregar preguntas</a></li>
                <li><a href="<?php echo $G->config['w_url'] ?>/preguntas/lista"><i class="fa fa-angle-double-right"></i> Lista de Preguntas</a></li>
                <li><a href="<?php echo $G->config['w_url'] ?>/preguntas/buscar"><i class="fa fa-angle-double-right"></i> Buscar Preguntas</a></li>
            </ul>
            <?php
        }
        ?>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-user"></i>
            <span>Usuarios</span>
            <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="<?php echo $G->config['w_url'] ?>/usuarios/agregar"><i class="fa fa-angle-double-right"></i> Agregar usuario</a></li>
            <li><a href="<?php echo $G->config['w_url'] ?>/usuarios/lista"><i class="fa fa-angle-double-right"></i> Listar usuarios</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-book"></i>
            <span>Reportes</span>
            <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="<?php echo $G->config['w_url'] ?>/reportes/preguntas"><i class="fa fa-angle-double-right"></i> Por Lenguaje</a></li>
        </ul>
    </li>
</ul>