<script src="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "js" . DS . "paginador.js" ?>" type="text/javascript"></script>

<section class="content-header">
    <h1>
        <?php echo strtoupper($G->act) . ' | '; ?> USUARIOS 
    </h1>
</section>
<section class="content">
    <div class="box box-danger">
        <?php if ($G->act == 'agregar') { ?>
            <div class="box-body">
                <form id="frmreg" method="post" class="form-horizontal" action="opcion">
                    <div class="col-lg-8">
                        <div class="form-group form-group-sm">
                            <label for="nombres" class="col-lg-2 control-label">Nombres</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" id="nombres" name="nombres" placeholder="Ingrese nombres" required>
                            </div>
                        </div>
                        <div class="form-group form-group-sm">
                            <label for="apellidos" class="col-lg-2 control-label">Apellidos</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" id="apellidos" name="apellidos" placeholder="Ingrese apellidos" required>
                            </div>
                        </div>
                        <div class="form-group form-group-sm">
                            <label for="nick" class="col-lg-2 control-label">Nickname</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" id="nick" name="nick" placeholder="Ingrese nickname" required>
                            </div>
                        </div>
                        <div class="form-group form-group-sm">
                            <label for="pass" class="col-lg-2 control-label">Contrase&ntilde;a</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" id="pass" name="pass" placeholder="Ingrese contrase&ntilde;a"  pattern="[0-9.]{1,9}" data-valid-min="1" required>
                            </div>
                        </div>
                        <div class="form-group form-group-sm">
                            <label for="sesion" class="col-lg-2 control-label">Sesi&oacute;n</label>
                            <div class="col-lg-4">
                                <input type="text" class="form-control" id="sesion" name="sesion"  disabled>
                            </div>
                            <label for="tipo" class="col-lg-2 control-label">Tipo</label>
                            <div class="col-lg-4">
                                <select id="tipo" name="tipo"  class="form-control">
                                    <option value="1">Administrador</option>
                                    <option value="3">Participante</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <div class="col-lg-6 col-lg-offset-4">
                            <a href="index"  class="btn btn-default">Atr&aacute;s</a>
                            <button type="reset" class="btn btn-danger" >Cancelar</button>
                            <button type="submit" class="btn btn-primary">Agregar</button>
                        </div>
                    </div>
                </form>
            </div>
        <?php } ?>
        <?php if ($G->act == 'lista') { ?>
            <table class="table table-hover" id="tblDatos">
                <thead>
                    <tr>
                        <th style='text-align: center'>#</th>
                        <th style='text-align: center'>NOMBRES</th>
                        <th style='text-align: center'>APELLIDOS</th>
                        <th style='text-align: center'>NICKNAME</th>
                        <th style='text-align: center'>TIPO</th>
                        <th style='text-align: center'>ESTADO</th>
                        <th style='text-align: center'>ACCION</th>
                    </tr>
                </thead>
                <tbody style='text-align: center' >
                    <tr><td colspan='9'>No hay resultados con esos datos</td></tr>
                </tbody>
            </table> 

            <!--<div id="paginador" class="btn btn-lg btn-primary"></div>-->
            <script type="text/javascript">
                // var p = new Paginador(document.getElementById('paginador'), document.getElementById('tblDatos'), 10);
                // p.Mostrar();
            </script>

            <h3>
                <!--<small>Lista <span class="label label-danger">Total de registros: <%out.println(totalElementos);%></span></small>-->
            </h3>
            <!--ul class="pagination">
        </ul-->
        <?php } ?>
    </div>
</section>