<?php
//Cargar el header de la pagina de Guest -->
$G->title = "Login";
loadView("guest/header.phtml");
?>
<style>
    body{
        background-image: url('app/media/images/binario.gif');
    }
</style>
        <div class="form-box" id="login-box">
            <div class="header">Ingresar usuario</div>
            <form method="post" action="">
                <input type="hidden" name="accion" value="IniciarSesion"/>
                <div class="body bg-gray">
                    <div class="form-group">
                        <input type="text" name="user" class="form-control" placeholder="Ingrese su nickname"/>
                    </div>
                    <div class="form-group">
                        <input type="password" name="pass" class="form-control" placeholder="Ingrese su Clave"/>
                    </div>          
                </div>
                <div class="footer">   
                       <?php

                if( !empty($G->error) && $G->error != "ok" ){
                    ?>
                <div class="alert alert-danger"><p><?php echo $G->error; ?></p></div>
                <?php
                }
                ?>
                    <button type="submit" class="btn bg-olive btn-block">Ingresar</button>  
                    <a href="registro.jsp" class="btn btn-info btn-block">Registrarme</a>
                </div>
            </form>
        </div>